# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pace < Formula
  desc "Command Line Interface for https://pace.io"
  homepage "https://pace.io"
  version "1.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getstrm/cli/releases/download/v1.6.0/pace_darwin_amd64.tar.gz"
      sha256 "cd95485d11fd1b6b70020287182282b51937339386b61a5b146a304daa9eec82"

      def install
        bin.install "pace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getstrm/cli/releases/download/v1.6.0/pace_darwin_arm64.tar.gz"
      sha256 "b5e2fdf90c28f863d6c05469fe142f2a24ea6c87fe0e71cd1ba9ce52044eddde"

      def install
        bin.install "pace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getstrm/cli/releases/download/v1.6.0/pace_linux_arm64.tar.gz"
      sha256 "e19ccd74832924ea3f896e0501902779ebc4df321b48db62f2a813c14aa6ebd2"

      def install
        bin.install "pace"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/getstrm/cli/releases/download/v1.6.0/pace_linux_amd64.tar.gz"
      sha256 "b752ca58c78128e57718012dcb7b90ae6677a674126c4254768e33f98a28b4bb"

      def install
        bin.install "pace"
      end
    end
  end

  def caveats
    <<~EOS
      In order to set up auto completion, please follow the instructions below. When you've set up auto completion in the past, you can skip these instructions.

       for bash users
         add the following line to your .bash_profile or .bashrc:
           source <(pace completion bash)

         to load completions for each session, execute once:
           - Linux users: pace completion bash > /etc/bash_completion.d/pace
           - macOS users: pace completion bash > /usr/local/etc/bash_completion.d/pace

       for zsh users
         ensure that shell completion is enabled, then run (only needs to be done once):
           pace completion zsh > "${fpath[1]}/_pace"

       for fish users
         pace completion fish > ~/.config/fish/completions/pace.fish # or $XDG_CONFIG_HOME instead of ~/.config
    EOS
  end

  test do
    system "#{bin}/pace --version"
  end
end
